# Generated by Django 4.2.1 on 2023-06-20 07:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0009_delete_blogpost_alter_question_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
